README.md, index.js, test.js
=> timePrecision support added

package.json
=> Feature/influxdb 0.9

index.js, test.js
=> Fix tag values escaping

index.js
Should respect the sorting requested by the user in their query.
Fixes #99
=> Remove broken sorting

index.js
#103 See issue.
Any feedback is welcome on this change. Different solution as well, because for me it is not clear why body is undefined.
=> Prevent crash when body is not defined.

index.js
getRetentionPolicies method is failing due to invalid query.
=> Add missing "on" in "show retention policies" query

index.d.ts, index.js
=> write-point: Fix cannot read database property error when missing options

index.js
=> Type checks response data, stops uncaught type error

LICENSE
=> Create LICENSE file so GitHub displays its icon

README.md, index.js, test.js
+ README improvements, tests, and more precise terminology.
=> Escape properly. Fix #96 for good.

index.js
Inspecting the InfluxDB responses during tests shows that many contain warnings such as:
```
deprecated use of 'DROP USER johnsmith' in a read only context, please use a POST request instead
deprecated use of 'CREATE USER johnsmith WITH PASSWORD [REDACTED] WITH ALL PRIVILEGES' in a read only context, please use a POST request instead
deprecated use of 'REVOKE ALL PRIVILEGES FROM johnsmith' in a read only context, please use a POST request instead
deprecated use of 'CREATE CONTINUOUS QUERY testQuery ON test_db BEGIN SELECT count(value) INTO test_db."default".valuesCount_1h FROM test_db."default".number_test GROUP BY time(1h) END' in a read only context, please use a POST request instead
deprecated use of 'DROP CONTINUOUS QUERY testQuery ON test_db' in a read only context, please use a POST …
```
=> Use POST instead of GET for DB update operations

index.js, test.js
=> Make all tests run independently

test.js
These seem to have gotten lost in the merge of PR #164.
=> Cosmetic test fixes (names, comments)

CONTRIBUTING.md
=> Update contributing links.

index.js
=> Added a non-failing error message when the body is empty

.travis.yml, README.md, esdoc.json, examples/testing.md, package.json, src/grammar/ds.ts, src/index.ts, test/fixture/integrateSampleData.json, test/integrate/admin.test.ts, test/integrate/data.test.ts, test/integrate/helpers.ts, test/lineToPoint.js, test/unit/backoff.test.ts, test/unit/builder.test.ts, test/unit/grammar.test.ts, test/unit/helpers.ts, test/unit/influx.test.ts, test/unit/pool.test.ts, test/unit/result.test.ts, test/unit/schema.test.ts
This adds base coverage to most methods, and adds a couple missing ones.
=> Integration tests

src/pool.ts
=> fix(pool) honour host.options.timeout in the browser

src/index.ts
Fixes #314 
- Add an example demonstrating https setup
- [na] A test has been added if appropriate
=> fix(docs): add an example for https. fixes #314

src/index.ts, test/create-fixtures.js, test/fixture/v1.0.0/showShards.json, test/integrate/data.test.ts, test/unit/helpers.ts, test/unit/influx.test.ts
Fixes #
- Add function showShards
-
-
=> feat: add function showShards

src/index.ts, test/integrate/data.test.ts, test/unit/influx.test.ts
Fixes #
- Add function dropShard
-
-
=> feat: add function dropShard

src/builder.ts
Fixes #
- Fix a doc string with a missing quotation mark
=> Fix documentation string

README.md
Removing Gitter badge due to inactivity.
- Remove Gitter Badge due to inactivity.
=> chore: remove gitter badge

package.json, src/index.ts, test/unit/influx.test.ts
- #500 but rebased and commit message in semantic format
=> feat: Placeholder support

renovate.json
- Enables Semver Ranges in package.json for Renovate
- Disables PR rate limit
=> chore(renovate): use semver + remove rate limit

README.md
Fixes outdated Travis CI badge in README
=> docs: update CI status badge

README.md
=> Mention the official client for v2+

.github/workflows/CI.yml, .github/workflows/release.yml
Fixes CI Failing to install stream-http from GitHub
=> Fix CI stream-http Access

.github/workflows/CI.yml, .github/workflows/release.yml
Upgrade to supported node.js versions.
---
=> fix(ci): update to modern node versions

.github/workflows/CI.yml
=> ci: update to currently maintained nodejs versions

.github/workflows/CI.yml
Fixes Code Coverage not being reported
Updates action to use Coveralls parallel strategy
---
=> ci: setup coveralls parallel reporting

.github/workflows/release.yml
=> fix(ci): semantic release

.github/workflows/CI.yml
=> chore: upgrade node version for testing to 18, 20, 22
