node-influx/node-influx

.travis.yml
README.md
index.js
lib/InfluxRequest.js
test.js

enables https support by setting protocol option to 'https'

added protocol option

---

index.js

Escape spaces and commas in seriesName - according to https://influxdb.com/docs/v0.9/write_protocols/line.html
fix https://github.com/node-influx/node-influx/issues/62 ?

Escape spaces and commas in seriesName

---

index.js
test.js

With the current client it is not possible to write strings because they need to be escaped properly.
See also #78.
Includes the bugfix and test.

Escape strings as values when writing points

---

index.js

the message is in body.error, not in body as string

fix for body error message

---

index.js

This fixes creation of continuous queries with dashes (-) in the name

Adding missing quotes on CREATE CONTINUOUS QUERY

---

lib/InfluxRequest.js

This makes is parallel other error cases, like ENOTFOUND.
Before, it would return 'No hosts available' for all resubmittable errors instead of the actual error
Getting the proper error code makes it possible to distinguish between different errors, for example:
ECONNREFUSED:  influxdb is not listening on this port
vs.
ETIMEOUT:  no response (perhaps due to a firewall)

Return errors (such as ECONNREFUSED) when you're out of hosts (in master)

---

index.js
test.js

This adds a test case and fixes encoding failures when trying to write data that contains a "length" key or value. Prior to these fixes the added test case would fail with:
Previously the \_.createKey*String was using `_.map` which, while it _worked_ over objects, was actually a lodash method to work on collections. Evidently the logic lodash used to decide whether something was a collection or an object was to see if it had a `length` key, so objects that did contain a length key were treated as arrays. This PR replaces it with `_.forOwn` to explicitly iterate over enumerable properties.

Fix encoding failues on objects containing a 'length' key

---

README.md
index.js
test.js

This adds support for configuring the client like this:
```js
var client = influx('http://dbuser:f4ncyp4ass@localhost:8060/my_database')
```
I find URLs very convenient for configuring things which require the data this client does (for example, in command line tools, so that only one command line switch is needed). Other example of a module which supports URLs in a similar fashion is [`redis`](https://www.npmjs.com/package/redis).
I am not sure if this should stick with the `http(s):` protocol, however. If user tried sending a request to a URL like this, they would get a 404. A thought of `influxdb(s):` protocol crossed my mind.

Support configuring the client using URLs

---

index.d.ts

This PR adds a TypeScript definition file which will be automatically detected for TypeScript 1.7+ (thanks to its `node` module resolution policy). It should greatly simplify integration into TypeScript projects as well as make navigating the codebase easier for tools which support TypeScript definition files for JavaScript.

Add TypeScript Definition

---

index.d.ts

Just a quick update to the TypeScript definition file to add support for #128 to it (as well as a couple extra doc comments).
In line with the contributing guidelines, I'll not merge this myself :+1:.

feat: Add constructor overload for #128 to TypeScript definition

---

index-test.ts
index.d.ts
package.json

This PR adds some small tests to help ensure we ship a valid definition file, primarily around compiling it and a very basic usecase (taken from the examples folder).
I've also rewritten the definition file to better support the `node` module resolution mode in TypeScript - it was previously targetting what is known as "ambient" or "global" inclusion, something which is being phased out as the compiler becomes more capable of resolving the correct definitions for various modules.

Add TypeScript Definition Tests

---

index.js
test.js

Had issues passing a series of points into the writeSeries function: subsequent points would have their time value stripped, and thus entered under the wrong timestamp.
It seems that during the `_.each` loop in `_prepareValues`, the `delete points[0].time` command got propagated to all points, which causes subsequent points to not have a `time` field in points[0], which then causes the method to write the current timestamp for the event, instead of the timestamp specified.

Moved removal of point[0].time to createKeyValueString method

---

index.js

Does what it says on the tin, passes the callback argument from `writePoints` into the `writeSeries` function.

fix #143: Correctly pass callback to writeSeries from writePoints

---

index.js

This resolves an issue when specifying options and calling `writePoints`
(or, by extension, `writePoint`) which would result in an exception
being thrown.
The exception itself is as follows:
```
Uncaught TypeError: callback is not a function
at $PROJECT\node_modules\influx\index.js:102:14
at InfluxRequest._parseCallback ($PROJECT\node_modules\influx\lib\InfluxRequest.js:122:10)
at Request._callback ($PROJECT\node_modules\influx\lib\InfluxRequest.js:111:10)
at Request.self.callback ($PROJECT\node_modules\request\request.js:200:22)
at Request.<anonymous> ($PROJECT\node_modules\request\request.js:1067:10)
at IncomingMessage.<anonymous> ($PROJECT\node_modules\request\request.js:988:12)
at endReadableNT (_stream_readable.js:926:12)
at _combinedTickCallback (internal/process/next_tick.js:74:11) …
```

fix: Don't duplicate options when calling writeSeries

---

.travis.yml
index.js
test.js

👋 
With Influx going on 1.0.0 and work towards a node-influx@5.0.0, I figured it was time we update tests to support 0.13. This tweaks the tests and also updates the getSeriesName to work with 0.11 and above; previously it would always returns an array like `[undefined]`.

Update tests, getSeriesName to support Influx 0.13

---

index.js

Some of influxDB versions give back error as JSON. And it will be automatically parsed by "request". 
In that case I have error message as [Object object].

Stringify error if an object

---

index.js
lib/InfluxRequest.js
test.js

Only whitespace fixes. Codebase lints clean after these changes.

Make existing code `standard` compliant

---

test.js

This PR refactors the test suite so that there are no dependencies between tests. This allows you to run individual tests or sub-suites (i.e. `mocha --grep users`).
Prior to this series of commits, three tests were already failing:
- InfluxDB #createDatabase should not throw an error if db already exists: `Error: database already exists`
- InfluxDB #query failover should read a point from the database after the failed servers have been removed: `Uncaught AssertionError: { Error: connect ENETUNREACH 192.168.255.2:8086`
- InfluxDB #dropDatabase should not error if database didn't exist: `Error: database not found: test_db`
The `#query failover` is fixed by permitting more retries so all the valid host is eventually selected in the first commit. The others are fixed individually by the final …

Refactor tests to eliminate inter-test dependencies

---

README.md

Started with `var point = { attr : value, time : new Date()};` being unused, and I ended up making the spacing consistent.

rm unused variable, fix syntax errors, make spacing consistent

---

index.js
test.js

Per [the docs](https://docs.influxdata.com/influxdb/v1.0/write_protocols/line_protocol_tutorial/#tag-set),
> For best performance you should sort tags by key before sending them to the database.

Sort tags before writing, for performance

---

README.md

https://github.com/node-influx/node-influx/blob/master/index.js#L12 uses the typo, so we may run into backcompat issues. Maybe slate it for v5, along with #182?

Fix typo "depreciated", but not in the options API

---

index.js

When an empty object is set for the pool in the options for the request module, a conditional fails which creates a new HTTPS agent rather than using the globalAgent that may have injected certificate authorities or global options.

Fix #206: globalAgent ignored during HTTPS communication

---

src/pool.ts

See #244 
The way of body's length measurement is wrong when the body contains multi-bytes characters.
Ignore the `content-length` header, it will automatically use `Transfer-Encoding: chunked`, works fine.

Fix incorrect content-length header cause request body being chopped

---

src/index.ts

* uniform `@return` vs `@returns`
* grammar fix for .query()
* fix return value description
Can't figure out why ESDoc didn't hyperlink "Promise" and especially IResults. Everywhere else "Promise" is hyperlinked to MDN.

.query typo fix, link IResults; consistent @return

---

src/doc.ts

The key name `timestamp` for IPoint is inconsistent with what `.query` returns (`time`), though...

Fix dupe IPoint key name and terminology

---

src/pool.ts
test/unit/pool.test.ts

In fact, the length of string in node may not be equal the actual string length, and the server will get wrong sql,so use Buffer to get the string length.
example:
var text='你好' // this string is chinese
console.log(text.length) will be 2,but actual it's  6.

fix get wrong http request body length

---

src/index.ts

getMeasurements is used twice instead of getDatabaseNames

Typo in docs

---

src/index.ts

It will default to 127.0.0.1
closes #318

feat: mark typescript definition for host optional

---

src/index.ts
test/unit/influx.test.ts

Fixes #311 - rebases stale changes from @flafik as per https://github.com/node-influx/node-influx/pull/311#issuecomment-497952278
- Allow a schema to be added to the `InfluxDB` object at runtime i.e. after the object has been initialised.  This makes field coercion work where the name of the database or measurement is not known prior to writing the points.

feat: allow schema to be specified at runtime

---

src/index.ts

- Fix the return type of `InfluxDB.getDatabaseNames()` according to its document
- This revision doesn't need to update any test files.

fix: correct return type of getDatabaseNames()

---

.editorconfig

Fixes #
- Replace space by tab in editorconfig, since eslint is checking for tabs
-
-

fix: bring editorconfig inline with eslint rules

---

src/index.ts
src/pool.ts
test/unit/influx.test.ts
test/unit/pool.test.ts

May be used if Influx is behind a reverse proxy or load balancer
Fixes #324 
I came across the same issue as described in this ticket. This PR provides a solution for this.
- Added optional `path` to host configuration. Default to empty string. Path is expected to start with a "/"
- `path` is added to the host URL for API calls
- I updated the tests as required
- I didn't add a test but I tested it with my server. Not sure how we could add a unit test, as in default InfluxDB installs, the path is empty.
- The path cannot be specified when passing the host configuration as a string. I thought it would be confusing since in that format, the path contains the database name.

Add 'path' configuration option for host

---

src/pool.ts

Fixes #475 
- The influx ping responses are consumed

Consume ping responses

---

src/pool.ts

Fixes #494
- HTTP requests are aborted on timeout in both `ping` and `stream` methods.

fix: abort requests on timeout

---

src/grammar/times.ts
test/unit/grammar.test.ts

Fixes #487
- issue related to floating-point arithmetics in JS.
- first proposal was to use third-party [big.js](https://github.com/MikeMcl/big.js), but actually could manage a workaround based on string parsing.
---

fix: fix timestamps rounding in INanoDate

---

src/pool.ts
test/unit/pool.test.ts

Fixes #521
Set response encoding to `utf8`, so string concentration when multiple chunks are received would work as expected.

fix: proper encoding for response in pool (#521)

---

.github/workflows/CI.yml

Fixes Github Actions CI workflow
- Remove commit SHA reference from `actions/checkout@v2` as is not required. Pushes on master will reference latest commit SHA and PRs will reference the merge commit.
---

ci: checkout pull request head

---

src/pool.ts

Fixes #542
- Consume response body on HTTP errors with status code >= 500
- Call stream callback only after response has been fully consumed
---

fix: consume response on http 500 errors

---

src/backoff/constant.ts
src/pool.ts
test/unit/backoff.test.ts
test/unit/pool.test.ts

Fixes #544 
- Check if host should be disabled. It's keep enabled if `host.fail()` (which calls the backoff getter) returns zero. It will only disable the host if this value is greater than zero.
- Add a constant backoff strategy as an alternative to the default exponential backoff. This was required to simplify test creation, but it also adds value for users that don't need exponential strategies.
- Create tests for ConstantBackoff class and add two tests for the Pool class to show the changed behaviour.
---

fix: don't disable pool host if backoff is zero

---

.github/workflows/release.yml

Kudos @bencevans for that fast migration to GH Actions!
Fix release workflows being executed on forks (they always fail, but waste user minutes).
- Restrict execution of release workflow based on repository name.
---

ci: restrict release workflow to upstream repository

---

src/index.ts
test/karma.conf.js
test/unit/influx.test.ts

Currently, the logic for validating a point is embedded in the InfluxDB.writePoints function. I am proposing to extract that logic out to a separate function on the InfluxDB instance so it will be used by InfluxDB.writePoints, but is also accessible externally for optional manual schema/coercion validation of a given point *before* being sent to InfluxDB.writePoints. This can be beneficial for "pre-processing" a batch of data to determine which points are valid and which are not, so they can be dealt with accordingly. This gives the user the flexibility to decide how validation is done and what to do if a data point is invalid.

#560 - Expose a "point validation" function

---

examples/testing.md
src/index.ts
src/pool.ts
test/integrate/admin.test.ts

Fixes #578
Add `Authorization` header to `ping` methods if `username` and `password` options have been defined.
No tests are required, as `ping` was already being tested. However, I did add some clarifications in the docs to suggest that testing should be done with authentication enabled and a `root` user created. Also, a fix has been included in a test helper method that checked the existence of an user. It was failing if other users existed besides the one being checked.
---

feat: support authentication in ping method

---

src/index.ts
test/unit/influx.test.ts

Fixes #539 
---
- [ x ] A test has been added if appropriate
- [ x ] `npm test` completes successfully
- [ x ] Commit messages are in [semantic format](https://seesparkbox.com/foundry/semantic_commit_messages)

fix: #539 Incorrect encoding when using placeholders / bind parameters

---

src/index.ts
test/unit/influx.test.ts

Fixes #587
Placeholders / bind parameters support for number variables

fix: #587 Placeholders / bind parameters support for number variables

---

.github/workflows/release.yml

Fixes CI Failing due to old node.js version
Run with Node.js 18
---

ci: release with node 18

---

src/index.ts
src/results.ts

Current type definitions for query results lack proper typing for the time field, which can lead to type-safety issues when working with time-series data. This PR adds proper typing to ensure the time field is correctly typed as `INanoDate` throughout the codebase.
1. **In `index.ts`**:
- Update return type of `query` method overloads to include `time: grammar.INanoDate`
- Modify generic type parameter to include time field type information
2. **In `results.ts`**:
- Update `parse` function return type to include `time: INanoDate` in generic type parameter
- **Note**: `parseInner` function still uses `any` and should be updated with proper type hints. If this is merged, I'll spend some time to properly type that function as well.
This improves TypeScript type safety when working with time …

fix: improve time field typing in query results

---

src/grammar/times.ts
test/unit/grammar.test.ts

Fixes #606
Correct issues caused by floating point errors when converting nano timestamps to ms
---

fix: #606 - Timestamp conversion subject to floating point errors

---

src/index.ts
src/pool.ts
test/fixture/pool-middleware.js
test/unit/influx.test.ts
test/unit/pool.test.ts

This feature replaces sending credentials in URL by using basic authentication in HTTP header.
Fixes #264, #323 
Initial test confirm it now [works with QuestDB](https://community.questdb.com/t/is-there-a-way-to-write-to-questdb-with-node-red/875/21?u=pdeng). Since this could be a breaking change for some people, I would like to ask the wider community to test and improve this PR.
- Remove credentials from connecting url
- Added basic authentication in http header
- Basic authentication is the default
- Modified tests
---

feat: default to Basic Auth header; stop sending creds in URL/query
